# Generated by Django 3.2.18 on 2023-04-26 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='post_date',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
