# Generated by Django 3.2.18 on 2023-04-26 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_item_post_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='post_date',
            new_name='date',
        ),
    ]
